dist: trusty
sudo: required

language: node_js
node_js:
  - "10"

branches:
  only:
    - deploy

notifications:
  email: false

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

before_deploy:
  - npm run build -- --prod --base-href https://yuryvegero.github.io/angular-mp-year2020

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/angular-mp-year2020
  on:
    branch: deploy
