language: node_js
node_js:
  - "12"

branches:
  only:
    - deploy

notifications:
  email: false

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run build --base-href angular-mp-year2020 --deploy-url angular-mp-year2020

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/angular-mp-year2020
  on:
    branch: deploy
